const tintColorLight = '#1c40f2';
const tintColorDark = '#4f7eff';

export default {
  light: {
    text: '#000000',
    textSecondary: '#6b7280',
    background: '#ffffff',
    backgroundSecondary: '#f9fafb',
    card: '#ffffff',
    cardBorder: '#e5e7eb',
    tint: tintColorLight,
    tabIconDefault: '#9ca3af',
    tabIconSelected: tintColorLight,
    buttonPrimary: '#1c40f2',
    buttonSecondary: '#e5e7eb',
    inputBackground: '#f9fafb',
    inputBorder: '#e5e7eb',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
    divider: '#e5e7eb',
    shadow: 'rgba(0, 0, 0, 0.1)',
  },
  dark: {
    text: '#ffffff',
    textSecondary: '#9ca3af',
    background: '#121212',
    backgroundSecondary: '#1c1c1e',
    card: '#1c1c1e',
    cardBorder: '#2c2c2e',
    tint: tintColorDark,
    tabIconDefault: '#6b7280',
    tabIconSelected: tintColorDark,
    buttonPrimary: '#1c40f2',
    buttonSecondary: '#2c2c2e',
    inputBackground: '#2c2c2e',
    inputBorder: '#3c3c3e',
    success: '#10b981',
    warning: '#f59e0b',
    error: '#ef4444',
    info: '#3b82f6',
    divider: '#2c2c2e',
    shadow: 'rgba(0, 0, 0, 0.3)',
  },
};